// <auto-generated />
using System;
using LoPartidet.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoPartidet.API.Migrations
{
    [DbContext(typeof(LoPartidetContext))]
    [Migration("20260406210231_AddIdentityIdToUser")]
    partial class AddIdentityIdToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LoPartidet.API.Entities.Match", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FootballType")
                        .HasColumnType("int");

                    b.Property<bool>("IsJoined")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("JoinedCount")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("MaxPeople")
                        .HasColumnType("int");

                    b.Property<string>("Organizer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Date = new DateTime(2026, 4, 10, 20, 0, 0, 0, DateTimeKind.Utc),
                            FootballType = 1,
                            IsJoined = true,
                            JoinedCount = 11,
                            Location = "Poliesportiu Les Corts, Barcelona",
                            MaxPeople = 14,
                            Organizer = "Marc Ribas",
                            Status = 0
                        },
                        new
                        {
                            Id = "2",
                            Date = new DateTime(2026, 4, 8, 19, 45, 0, 0, DateTimeKind.Utc),
                            FootballType = 0,
                            IsJoined = true,
                            JoinedCount = 10,
                            Location = "Pista Municipal Nord, Madrid",
                            MaxPeople = 10,
                            Organizer = "Luis Herrera",
                            Status = 1
                        },
                        new
                        {
                            Id = "3",
                            Date = new DateTime(2026, 4, 6, 17, 30, 0, 0, DateTimeKind.Utc),
                            FootballType = 3,
                            IsJoined = false,
                            JoinedCount = 12,
                            Location = "Pavelló Can Zam, Santa Coloma",
                            MaxPeople = 12,
                            Organizer = "Jordi Puig",
                            Status = 2
                        },
                        new
                        {
                            Id = "4",
                            Date = new DateTime(2026, 4, 12, 11, 0, 0, 0, DateTimeKind.Utc),
                            FootballType = 2,
                            IsJoined = false,
                            JoinedCount = 14,
                            Location = "Camp Municipal de Futbol, Badalona",
                            MaxPeople = 22,
                            Organizer = "Sergio Mora",
                            Status = 0
                        },
                        new
                        {
                            Id = "5",
                            Date = new DateTime(2026, 4, 13, 10, 30, 0, 0, DateTimeKind.Utc),
                            FootballType = 4,
                            IsJoined = true,
                            JoinedCount = 8,
                            Location = "Platja de la Barceloneta, Barcelona",
                            MaxPeople = 10,
                            Organizer = "Alex Font",
                            Status = 0
                        });
                });

            modelBuilder.Entity("LoPartidet.API.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("JerseyNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Position")
                        .HasColumnType("int");

                    b.Property<int?>("PreferredFoot")
                        .HasColumnType("int");

                    b.Property<int?>("SkillLevel")
                        .HasColumnType("int");

                    b.Property<int?>("Speed")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LoPartidet.API.Entities.UserMatch", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MatchId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "MatchId");

                    b.HasIndex("MatchId");

                    b.ToTable("UserMatches");
                });

            modelBuilder.Entity("LoPartidet.API.Entities.UserMatch", b =>
                {
                    b.HasOne("LoPartidet.API.Entities.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoPartidet.API.Entities.User", "User")
                        .WithMany("UserMatches")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LoPartidet.API.Entities.User", b =>
                {
                    b.Navigation("UserMatches");
                });
#pragma warning restore 612, 618
        }
    }
}
